# my_tuple = (10,20,30,40,50)
# print(my_tuple)

# my_tuple = (10,20,30,40,50)
# print(my_tuple[2])

# my_tuple = (1,2,3,4,5)
# print(my_tuple[-1])

# my_tuple = (5,10,15,20)
# print(len(my_tuple))

# my_tuples = (10,20,30,40,50)
# print(20 in my_tuples)

# mytuple = (2,4,6,8)
# for i in mytuple:
#     print(i)

# mytuple = (0,1,2,3,4,5,6,7,8,9)
# print(mytuple[1:4])

# mytuple = (1,2,3,4,5)
# mytuple = 2

# add= tuple(mytuple)
# print(add)

# mytuple = (1,2,2,3,4,2)
# print(mytuple.count(2))
# print(mytuple.index(3))

# my_tuple = (10,20,(30,40,50))
# print(my_tuple[2])
# print(my_tuple[2][1])

# ab =(10,90,(39,90,89,56),90,80)
# print(ab[2][2])

# ab= (10,20,30)
# t = list(ab)
# t.append(40)
# print(t)

# ab = (1,2,3,4,5,6)
# t = list(ab)
# t.append(7)
# print(t)

#sets--
#1.
# my_sets = {10,20,30,40}
# print(my_sets)
# print(type(my_sets))

#2.
# my_list = [1,2,3,4,5]
# my_list = set(my_list)
# print(my_list)
#3.
# my_set = {1,2,3,4,5}
# my_set.add(5)
# print(my_set)

#4.
# myset = {10,20,30,40}
# myset.remove(20)
# print(myset)

#5.
# set1 = {1,2,3}
# set2 = {3,4,5}
# myset = set1.union(set2)
# print(my_set)

#6.
# set1 = {1,2,3}
# set2 = {3,4,5}
# myset = set1.intersection(set2)
# print(myset)

#7.
# setA = {1,2,3,4}
# setB = {3,4,5,6}
# myset = setA.difference(setB)
# print(myset)

#8.
# set = {5,10,15,20,25}
# print("yes 10 is present")

#9.
# x = {1,2,3}
# x.clear()
# print(x)

#10.
# p = {1,2,3}
# q = {1,2,3}
# if p == q:
#     print("p and q equal")
# else:
#     print("not equal")

#Python Practice Questions--

# x = [10, 20, 20, 30, 40, 40, 50]
# dataset = set(x)
# print(dataset)

# list =[1,1,1,2,3,3]
# unique_set = set(list)
# print(unique_set)

# list = [5,6,7,7,8,9,9]
# my_set = set(list)
# print(my_set)
# my_set1 = len(my_set)
# print(my_set1)

# list = [3,3,2,1,2,4,5]
# my_set = set(list)
# print(my_set)
# print(sorted(my_set))

#function 
# def add2sum(a,b):
#     return  a+b
# result = add2sum(10,20)
# print(result)



